[tool.black]
line-length = 88
target-version = ["py313"]

[tool.ruff]
line-length = 88
target-version = "py313"

exclude = [
    ".git",
    ".venv",
    "__pycache__",
    ".ruff_cache",
    ".pytest_cache",
    "alembic/versions",
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
]

ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
]
[tool.pytest.ini_options]
testpaths = ["app/tests"]
addopts = [
    "--cov=app",
    "--cov-report=term-missing",
    "--cov-report=xml",
    "--cov-report=html",
]

[tool.coverage.run]
source = ["app"]
omit = [
    "app/tests/*",
]

[tool.coverage.report]
show_missing = true
skip_covered = false
precision = 2

exclude_lines = [
    "pragma: no cover",
    "if TYPE_CHECKING:",
    "raise NotImplementedError",
]